# Offense count: 9
Metrics/AbcSize:
  Max: 102

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 115

# Offense count: 7
Metrics/CyclomaticComplexity:
  Max: 28

Metrics/LineLength:
  Enabled: false

# Offense count: 8
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 60

# Offense count: 7
Metrics/PerceivedComplexity:
  Max: 29

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
