AllCops:
  DisplayCopNames: true

# Target: 15
Metrics/AbcSize:
  Max: 24
  Exclude:
    - lib/websocket/frame/handler/handler75.rb
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

# Target: 6
Metrics/CyclomaticComplexity:
  Max: 11
  Exclude:
    - spec/support/handshake_requests.rb

Metrics/LineLength:
  Enabled: false

# Target: 10
Metrics/MethodLength:
  Max: 18
  Exclude:
    - lib/websocket/frame/handler/handler75.rb

# Target: 7
Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - lib/websocket/frame/handler/handler75.rb
    - spec/support/handshake_requests.rb

Style/Documentation:
  Enabled: false

Layout/IndentHeredoc:
  Exclude:
    - spec/support/handshake_requests.rb

Style/SymbolArray:
  Enabled: false # Support for 1.9.3
