# Target: 15
Metrics/AbcSize:
  Max: 29
  Exclude:
    - lib/websocket/frame/handler/handler75.rb
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

# Target: 6
Metrics/CyclomaticComplexity:
  Max: 11
  Exclude:
    - spec/support/handshake_requests.rb

Metrics/LineLength:
  Enabled: false

# Target: 10
Metrics/MethodLength:
  Max: 31

# Target: 7
Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - spec/support/handshake_requests.rb

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
