# Offense count: 9
Metrics/AbcSize:
  Max: 102

# Offense count: 2
Metrics/BlockNesting:
  Max: 4

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 115

# Offense count: 7
Metrics/CyclomaticComplexity:
  Max: 28

# Offense count: 157
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 190

# Offense count: 8
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 60

# Offense count: 7
Metrics/PerceivedComplexity:
  Max: 29

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
