# Target: 15
Metrics/AbcSize:
  Max: 54

Metrics/ClassLength:
  Enabled: false

# Target: 6
Metrics/CyclomaticComplexity:
  Max: 16

Metrics/LineLength:
  Enabled: false

# Target: 10
Metrics/MethodLength:
  Max: 31

# Target: 7
Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
