dist: trusty
language: ruby
script: "bundle exec rake"
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem update bundler
