dist: trusty
language: ruby
script: "bundle exec rake"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0 # https://github.com/travis-ci/packer-templates/issues/393
  - ruby-head
  - jruby
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem update --system
  - gem update bundler
